CREATE TABLE TABLE_A (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT
);
CREATE TABLE TABLE_B (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT
);
CREATE TABLE TABLE_C (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT
);

create trigger name5 
on TABLE_A
AFTER INSERT 
AS
BEGIN 
 INSERT INTO TABLE_B (ID, NAME ,AGE)
 SELECT ID , NAME , AGE FROM  TABLE_A 
END

INSERT INTO TABLE_A (ID, NAME, AGE)
VALUES
    (1, 'John Doe', 25),
    (2, 'Jane Smith', 30),
    (3, 'Michael Johnson', 28),
    (4, 'Emily Brown', 22),
    (5, 'William Lee', 27);

SELECT * FROM TABLE_B;

CREATE TRIGGER NAME6 
ON TABLE_A 
AFTER DELETE 
AS 
BEGIN 
  INSERT INTO TABLE_C (ID, NAME ,AGE)
  SELECT ID , NAME , AGE
  FROM DELETED 
END
 
DROP TRIGGER NAME6;

DELETE FROM TABLE_A WHERE AGE >26;

SELECT * FROM TABLE_C;